### ISSUE TITLE
Include install instructions

### ISSUE THREAD

**Issue by BjoernLudwig** [mgrub/gitstatus#1]
Awesome work! Thanks for providing access to it. Would it be possible to add a short hint on where to put the files to make use of the functionality?

**Comment by mgrub** [comment]
Hey @BjoernLudwigPTB : Good point. I prepared the publication to CTAN during the last few days and now:

- the package is on [CTAN](https://www.ctan.org/pkg/gitstatus): 
- there is a nice [pdf documentation](https://github.com/mgrub/gitstatus/releases/download/v1.1.1/gitstatus.pdf)
- based on your suggestion, I provided a [installation helper](https://github.com/mgrub/gitstatus/blob/main/package_helper.md)

**Comment by BjoernLudwig** [comment]
That's beautiful! Thank for your work on that! Would it be appropriate to link the nice [package_helper.md](https://github.com/mgrub/gitstatus/blob/main/package_helper.md) in your README?
